#!/bin/sh
echo "what is your name?"
read name
echo "How are you, $name?"
read response
echo "I am $response too!"

#readonly name
NAME="Mahesh Kumar"
readonly NAME
NAME="Qadiri"


#unset name

fname="Farhan"
unset fname
echo $fname


#special variables

# $?  $@ $# $* $$ 

for var in $*
do 
echo $var
done



